# ETL Pipeline Preparation
Follow the instructions below to help you create your ETL pipeline.
### 1. Import libraries and load datasets.
- Import Python libraries
- Load `messages.csv` into a dataframe and inspect the first few lines.
- Load `categories.csv` into a dataframe and inspect the first few lines.

In [32]:
# import libraries
import pandas as pd
from sqlalchemy import create_engine

In [50]:
# load messages dataset
messages = pd.read_csv('messages.csv')
messages.head(30)

,id,message,original,genre
0,2,Weather update - a cold front from Cuba that c...,Un front froid se retrouve sur Cuba ce matin. ...,direct
1,7,Is the Hurricane over or is it not over,Cyclone nan fini osinon li pa fini,direct
2,8,Looking for someone but no name,"Patnm, di Maryani relem pou li banm nouvel li ...",direct
3,9,UN reports Leogane 80-90 destroyed. Only Hospi...,UN reports Leogane 80-90 destroyed. Only Hospi...,direct
4,12,"says: west side of Haiti, rest of the country ...",facade ouest d Haiti et le reste du pays aujou...,direct
5,14,Information about the National Palace-,Informtion au nivaux palais nationl,direct
6,15,Storm at sacred heart of jesus,Cyclone Coeur sacr de jesus,direct
7,16,"Please, we need tents and water. We are in Sil...",Tanpri nou bezwen tant avek dlo nou zon silo m...,direct
8,17,"I would like to receive the messages, thank you",Mwen ta renmen jouin messag yo. Merci,direct
9,18,I am in Croix-des-Bouquets. We have health iss...,"Nou kwadebouke, nou gen pwoblem sant m yo nan ...",direct
10,20,"There's nothing to eat and water, we starving ...",Bon repo pa gen anyen menm grangou swaf,direct
11,21,I am in Petionville. I need more information r...,M nan pv mvle plis enfomasyon sou 4636,direct
12,22,"I am in Thomassin number 32, in the area named...",Mwen thomassin 32 nan pyron mwen ta renmen jwe...,direct
13,24,"Let's do it together, need food in Delma 75, i...",Ann fel ansanm bezwen manje nan delma 75 nan r...,direct
14,25,More information on the 4636 number in order f...,gen plis enfomasyon sou 4636 la pom w sim ap k...,direct
15,26,"A Comitee in Delmas 19, Rue ( street ) Janvier...",Komite katye delma 19 rue janvier imp charite ...,direct
16,27,We need food and water in Klecin 12. We are dy...,Nou bezwen mange avek dlo nan klcin 12 LA LAFI...,direct
17,28,are you going to call me or do you want me to ...,Eske se rele nap relem oubyen se mwen kap rele...,direct
18,30,I don't understand how to use this thing 4636.,Mwen pa konprann koman pou m itilize bagay 463...,direct
19,31,I would like to know if the earthquake is over...,Mwen ta remen connin si trenblem de terre afin...,direct
20,32,I would like to know if one of the radio ginen...,Mwen ta renmen konnen eske ge jounalis radyo g...,direct
21,33,"I'm in Laplaine, I am a victim",Mwen laplan mwen viktim kot yap bay d pou latr...,direct
22,34,"There's a lack of water in Moleya, please info...",Nan moleya pa gen dlo svp f konnen sa pou mwen.,direct
23,35,Those people who live at Sibert need food they...,nou menm nan sibert nou grangou nou bezwen mange,direct
24,36,"I want to say hello, my message is to let you ...",Mwen salye nou dab mesaj mwen an se jis nou ge...,direct
25,37,Can you tell me about this service,Can you tell me about this service,direct
26,38,"People I'm at Delma 2, we don't anything what ...",MEZANMI MWEN MWEN NAN DELMA 2 NOU TR MAN MAL N...,direct
27,39,We are at Gressier we needs assistance right a...,Se gressier nou an difikilte tanpri vin ede nou,direct
28,41,How can we get water and food in Fontamara 43 ...,Comment nou ka jwen dlo ak manje nan font 43 c...,direct
29,42,We need help. Carrefour has been forgotten com...,Nap di secours yo bliye kafou net sant m ap to...,direct

In [49]:
# load categories dataset
categories = pd.read_csv ('categories.csv')
categories.head(200)

      id                                         categories
0      2  related-1;request-0;offer-0;aid_related-0;medi...
1      7  related-1;request-0;offer-0;aid_related-1;medi...
2      8  related-1;request-0;offer-0;aid_related-0;medi...
3      9  related-1;request-1;offer-0;aid_related-1;medi...
4     12  related-1;request-0;offer-0;aid_related-0;medi...
5     14  related-0;request-0;offer-0;aid_related-0;medi...
6     15  related-1;request-0;offer-0;aid_related-0;medi...
7     16  related-1;request-1;offer-0;aid_related-1;medi...
8     17  related-0;request-0;offer-0;aid_related-0;medi...
9     18  related-1;request-1;offer-0;aid_related-1;medi...
10    20  related-1;request-1;offer-0;aid_related-1;medi...
11    21  related-0;request-0;offer-0;aid_related-0;medi...
12    22  related-1;request-1;offer-0;aid_related-1;medi...
13    24  related-1;request-1;offer-0;aid_related-1;medi...
14    25  related-1;request-0;offer-0;aid_related-0;medi...
15    26  related-1;request-1;offer-0;aid_related-1;medi...
16    27  related-1;request-1;offer-0;aid_related-1;medi...
17    28  related-0;request-0;offer-0;aid_related-0;medi...
18    30  related-0;request-0;offer-0;aid_related-0;medi...
19    31  related-1;request-0;offer-0;aid_related-0;medi...
20    32  related-1;request-0;offer-0;aid_related-0;medi...
21    33  related-1;request-1;offer-0;aid_related-1;medi...
22    34  related-1;request-1;offer-0;aid_related-1;medi...
23    35  related-1;request-1;offer-0;aid_related-1;medi...
24    36  related-1;request-0;offer-0;aid_related-0;medi...
25    37  related-0;request-0;offer-0;aid_related-0;medi...
26    38  related-1;request-1;offer-0;aid_related-1;medi...
27    39  related-1;request-1;offer-0;aid_related-1;medi...
28    41  related-1;request-1;offer-0;aid_related-1;medi...
29    42  related-1;request-1;offer-0;aid_related-1;medi...
..   ...                                                ...
170  210  related-1;request-1;offer-0;aid_related-1;medi...
171  211  related-1;request-0;offer-0;aid_related-1;medi...
172  212  related-1;request-1;offer-0;aid_related-1;medi...
173  213  related-1;request-1;offer-0;aid_related-1;medi...
174  214  related-1;request-1;offer-0;aid_related-1;medi...
175  215  related-0;request-0;offer-0;aid_related-0;medi...
176  216  related-1;request-0;offer-0;aid_related-0;medi...
177  217  related-1;request-0;offer-0;aid_related-1;medi...
178  218  related-0;request-0;offer-0;aid_related-0;medi...
179  219  related-1;request-1;offer-0;aid_related-1;medi...
180  220  related-1;request-0;offer-0;aid_related-0;medi...
181  221  related-1;request-1;offer-0;aid_related-1;medi...
182  222  related-1;request-0;offer-0;aid_related-1;medi...
183  223  related-1;request-1;offer-0;aid_related-1;medi...
184  224  related-1;request-1;offer-0;aid_related-1;medi...
185  225  related-1;request-1;offer-0;aid_related-1;medi...
186  226  related-1;request-1;offer-0;aid_related-1;medi...
187  227  related-1;request-1;offer-0;aid_related-1;medi...
188  228  related-1;request-1;offer-0;aid_related-1;medi...
189  229  related-1;request-1;offer-0;aid_related-1;medi...
190  230  related-1;request-1;offer-0;aid_related-1;medi...
191  231  related-1;request-1;offer-0;aid_related-1;medi...
192  233  related-1;request-1;offer-0;aid_related-1;medi...
193  234  related-1;request-0;offer-0;aid_related-0;medi...
194  235  related-1;request-1;offer-0;aid_related-1;medi...
195  236  related-1;request-1;offer-0;aid_related-1;medi...
196  237  related-1;request-1;offer-0;aid_related-1;medi...
197  238  related-1;request-1;offer-0;aid_related-1;medi...
198  239  related-1;request-1;offer-0;aid_related-1;medi...
199  240  related-1;request-1;offer-0;aid_related-1;medi...

[200 rows x 2 columns]

### 2. Merge datasets.
- Merge the messages and categories datasets using the common id
- Assign this combined dataset to `df`, which will be cleaned in the following steps

In [35]:
# merge datasets
df = messages.merge(categories, on='id')
df.head()

,id,message,original,genre,categories
0,2,Weather update - a cold front from Cuba that c...,Un front froid se retrouve sur Cuba ce matin. ...,direct,related-1;request-0;offer-0;aid_related-0;medi...
1,7,Is the Hurricane over or is it not over,Cyclone nan fini osinon li pa fini,direct,related-1;request-0;offer-0;aid_related-1;medi...
2,8,Looking for someone but no name,"Patnm, di Maryani relem pou li banm nouvel li ...",direct,related-1;request-0;offer-0;aid_related-0;medi...
3,9,UN reports Leogane 80-90 destroyed. Only Hospi...,UN reports Leogane 80-90 destroyed. Only Hospi...,direct,related-1;request-1;offer-0;aid_related-1;medi...
4,12,"says: west side of Haiti, rest of the country ...",facade ouest d Haiti et le reste du pays aujou...,direct,related-1;request-0;offer-0;aid_related-0;medi...

### 3. Split `categories` into separate category columns.
- Split the values in the `categories` column on the `;` character so that each value becomes a separate column. You'll find [this method](https://pandas.pydata.org/pandas-docs/version/0.23/generated/pandas.Series.str.split.html) very helpful! Make sure to set `expand=True`.
- Use the first row of categories dataframe to create column names for the categories data.
- Rename columns of `categories` with new column names.

In [36]:
# create a dataframe of the 36 individual category columns
categories = df['categories'].str.split(';' , expand=True)
categories.head()

,0,1,2,3,4,5,6,7,8,9,...,26,27,28,29,30,31,32,33,34,35
0,related-1,request-0,offer-0,aid_related-0,medical_help-0,medical_products-0,search_and_rescue-0,security-0,military-0,child_alone-0,...,aid_centers-0,other_infrastructure-0,weather_related-0,floods-0,storm-0,fire-0,earthquake-0,cold-0,other_weather-0,direct_report-0
1,related-1,request-0,offer-0,aid_related-1,medical_help-0,medical_products-0,search_and_rescue-0,security-0,military-0,child_alone-0,...,aid_centers-0,other_infrastructure-0,weather_related-1,floods-0,storm-1,fire-0,earthquake-0,cold-0,other_weather-0,direct_report-0
2,related-1,request-0,offer-0,aid_related-0,medical_help-0,medical_products-0,search_and_rescue-0,security-0,military-0,child_alone-0,...,aid_centers-0,other_infrastructure-0,weather_related-0,floods-0,storm-0,fire-0,earthquake-0,cold-0,other_weather-0,direct_report-0
3,related-1,request-1,offer-0,aid_related-1,medical_help-0,medical_products-1,search_and_rescue-0,security-0,military-0,child_alone-0,...,aid_centers-0,other_infrastructure-0,weather_related-0,floods-0,storm-0,fire-0,earthquake-0,cold-0,other_weather-0,direct_report-0
4,related-1,request-0,offer-0,aid_related-0,medical_help-0,medical_products-0,search_and_rescue-0,security-0,military-0,child_alone-0,...,aid_centers-0,other_infrastructure-0,weather_related-0,floods-0,storm-0,fire-0,earthquake-0,cold-0,other_weather-0,direct_report-0

In [37]:
# select the first row of the categories dataframe
row = df['categories'].str.split(';' , expand=True).iloc[0].values.tolist()

# use this row to extract a list of new column names for categories.
# one way is to apply a lambda function that takes everything 
# up to the second to last character of each string with slicing
category_colnames = [r.split('-')[0]for r in row ]
print(category_colnames)

['related', 'request', 'offer', 'aid_related', 'medical_help', 'medical_products', 'search_and_rescue', 'security', 'military', 'child_alone', 'water', 'food', 'shelter', 'clothing', 'money', 'missing_people', 'refugees', 'death', 'other_aid', 'infrastructure_related', 'transport', 'buildings', 'electricity', 'tools', 'hospitals', 'shops', 'aid_centers', 'other_infrastructure', 'weather_related', 'floods', 'storm', 'fire', 'earthquake', 'cold', 'other_weather', 'direct_report']

In [38]:
# rename the columns of `categories`
categories.columns = category_colnames
categories.head()

,related,request,offer,aid_related,medical_help,medical_products,search_and_rescue,security,military,child_alone,...,aid_centers,other_infrastructure,weather_related,floods,storm,fire,earthquake,cold,other_weather,direct_report
0,related-1,request-0,offer-0,aid_related-0,medical_help-0,medical_products-0,search_and_rescue-0,security-0,military-0,child_alone-0,...,aid_centers-0,other_infrastructure-0,weather_related-0,floods-0,storm-0,fire-0,earthquake-0,cold-0,other_weather-0,direct_report-0
1,related-1,request-0,offer-0,aid_related-1,medical_help-0,medical_products-0,search_and_rescue-0,security-0,military-0,child_alone-0,...,aid_centers-0,other_infrastructure-0,weather_related-1,floods-0,storm-1,fire-0,earthquake-0,cold-0,other_weather-0,direct_report-0
2,related-1,request-0,offer-0,aid_related-0,medical_help-0,medical_products-0,search_and_rescue-0,security-0,military-0,child_alone-0,...,aid_centers-0,other_infrastructure-0,weather_related-0,floods-0,storm-0,fire-0,earthquake-0,cold-0,other_weather-0,direct_report-0
3,related-1,request-1,offer-0,aid_related-1,medical_help-0,medical_products-1,search_and_rescue-0,security-0,military-0,child_alone-0,...,aid_centers-0,other_infrastructure-0,weather_related-0,floods-0,storm-0,fire-0,earthquake-0,cold-0,other_weather-0,direct_report-0
4,related-1,request-0,offer-0,aid_related-0,medical_help-0,medical_products-0,search_and_rescue-0,security-0,military-0,child_alone-0,...,aid_centers-0,other_infrastructure-0,weather_related-0,floods-0,storm-0,fire-0,earthquake-0,cold-0,other_weather-0,direct_report-0

### 4. Convert category values to just numbers 0 or 1.
- Iterate through the category columns in df to keep only the last character of each string (the 1 or 0). For example, `related-0` becomes `0`, `related-1` becomes `1`. Convert the string to a numeric value.
- You can perform [normal string actions on Pandas Series](https://pandas.pydata.org/pandas-docs/stable/text.html#indexing-with-str), like indexing, by including `.str` after the Series. You may need to first convert the Series to be of type string, which you can do with `astype(str)`.

In [39]:
for column in categories:
    # set each value to be the last character of the string
    categories[column] = categories[column].str.split('-').str.get(1)
    
    # convert column from string to numeric
    categories[column] = categories[column].astype(int)
    categories.head()

### 5. Replace `categories` column in `df` with new category columns.
- Drop the categories column from the df dataframe since it is no longer needed.
- Concatenate df and categories data frames.

In [40]:
# drop the original categories column from `df`
df.drop('categories', axis=1 , inplace=True)

df.head(40)

,id,message,original,genre
0,2,Weather update - a cold front from Cuba that c...,Un front froid se retrouve sur Cuba ce matin. ...,direct
1,7,Is the Hurricane over or is it not over,Cyclone nan fini osinon li pa fini,direct
2,8,Looking for someone but no name,"Patnm, di Maryani relem pou li banm nouvel li ...",direct
3,9,UN reports Leogane 80-90 destroyed. Only Hospi...,UN reports Leogane 80-90 destroyed. Only Hospi...,direct
4,12,"says: west side of Haiti, rest of the country ...",facade ouest d Haiti et le reste du pays aujou...,direct
5,14,Information about the National Palace-,Informtion au nivaux palais nationl,direct
6,15,Storm at sacred heart of jesus,Cyclone Coeur sacr de jesus,direct
7,16,"Please, we need tents and water. We are in Sil...",Tanpri nou bezwen tant avek dlo nou zon silo m...,direct
8,17,"I would like to receive the messages, thank you",Mwen ta renmen jouin messag yo. Merci,direct
9,18,I am in Croix-des-Bouquets. We have health iss...,"Nou kwadebouke, nou gen pwoblem sant m yo nan ...",direct
10,20,"There's nothing to eat and water, we starving ...",Bon repo pa gen anyen menm grangou swaf,direct
11,21,I am in Petionville. I need more information r...,M nan pv mvle plis enfomasyon sou 4636,direct
12,22,"I am in Thomassin number 32, in the area named...",Mwen thomassin 32 nan pyron mwen ta renmen jwe...,direct
13,24,"Let's do it together, need food in Delma 75, i...",Ann fel ansanm bezwen manje nan delma 75 nan r...,direct
14,25,More information on the 4636 number in order f...,gen plis enfomasyon sou 4636 la pom w sim ap k...,direct
15,26,"A Comitee in Delmas 19, Rue ( street ) Janvier...",Komite katye delma 19 rue janvier imp charite ...,direct
16,27,We need food and water in Klecin 12. We are dy...,Nou bezwen mange avek dlo nan klcin 12 LA LAFI...,direct
17,28,are you going to call me or do you want me to ...,Eske se rele nap relem oubyen se mwen kap rele...,direct
18,30,I don't understand how to use this thing 4636.,Mwen pa konprann koman pou m itilize bagay 463...,direct
19,31,I would like to know if the earthquake is over...,Mwen ta remen connin si trenblem de terre afin...,direct
20,32,I would like to know if one of the radio ginen...,Mwen ta renmen konnen eske ge jounalis radyo g...,direct
21,33,"I'm in Laplaine, I am a victim",Mwen laplan mwen viktim kot yap bay d pou latr...,direct
22,34,"There's a lack of water in Moleya, please info...",Nan moleya pa gen dlo svp f konnen sa pou mwen.,direct
23,35,Those people who live at Sibert need food they...,nou menm nan sibert nou grangou nou bezwen mange,direct
24,36,"I want to say hello, my message is to let you ...",Mwen salye nou dab mesaj mwen an se jis nou ge...,direct
25,37,Can you tell me about this service,Can you tell me about this service,direct
26,38,"People I'm at Delma 2, we don't anything what ...",MEZANMI MWEN MWEN NAN DELMA 2 NOU TR MAN MAL N...,direct
27,39,We are at Gressier we needs assistance right a...,Se gressier nou an difikilte tanpri vin ede nou,direct
28,41,How can we get water and food in Fontamara 43 ...,Comment nou ka jwen dlo ak manje nan font 43 c...,direct
29,42,We need help. Carrefour has been forgotten com...,Nap di secours yo bliye kafou net sant m ap to...,direct
30,43,"Good evening, Radio one please. I would like i...",Bonswa radio one svp eskew pap k enfomasyon so...,direct
31,44,We have a lot of problem at Delma 75 Avenue Al...,We have a many probleme a baout delmas 75 aven...,direct
32,45,"I'm here, I didn't find the person that I need...",Mwen la moun poum te voye pantalon mwen pa jwe...,direct
33,46,People have been sleeping outdoors in a field ...,ofit des habitants qui dorment a la belle etoi...,direct
34,47,"We want you to know that Carrefour need help, ...",koufou poko jwenn ankenn ed nap mouri grangou ...,direct
35,48,How we can find food and water? we have people...,Comment nou ka jwen dlo ak manje nou gen moun ...,direct
36,49,"Delmas 33 in Silo, need water.",Delma 33 silo gen problem dlo,direct
37,50,I would like to get help at Cote Plage in Carr...,Mwen ta renmen yo vizite cote plage carrefour,direct
38,51,"I am in Leoganes, where can I get food? Please",mwen leyogan ki kote ki gen manje tanpri,direct
39,52,The Comite Miracle in the area of Alerte Rue M...,komite mirak ki tabli nan zone alerte mgr guil...,direct

In [41]:
# concatenate the original dataframe with the new `categories` dataframe
df=pd.concat([df,categories ], axis=1)
df.head()

,id,message,original,genre,related,request,offer,aid_related,medical_help,medical_products,...,aid_centers,other_infrastructure,weather_related,floods,storm,fire,earthquake,cold,other_weather,direct_report
0,2,Weather update - a cold front from Cuba that c...,Un front froid se retrouve sur Cuba ce matin. ...,direct,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,7,Is the Hurricane over or is it not over,Cyclone nan fini osinon li pa fini,direct,1,0,0,1,0,0,...,0,0,1,0,1,0,0,0,0,0
2,8,Looking for someone but no name,"Patnm, di Maryani relem pou li banm nouvel li ...",direct,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,9,UN reports Leogane 80-90 destroyed. Only Hospi...,UN reports Leogane 80-90 destroyed. Only Hospi...,direct,1,1,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
4,12,"says: west side of Haiti, rest of the country ...",facade ouest d Haiti et le reste du pays aujou...,direct,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

### 6. Remove duplicates.
- Check how many duplicates are in this dataset.
- Drop the duplicates.
- Confirm duplicates were removed.

In [42]:
# check number of duplicates
df.duplicated().sum()

170

In [43]:
# drop duplicates
df.drop_duplicates(inplace = True)

In [44]:
# check number of duplicates
df.duplicated().sum()

0

### 7. Save the clean dataset into an sqlite database.
You can do this with pandas [`to_sql` method](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.to_sql.html) combined with the SQLAlchemy library. Remember to import SQLAlchemy's `create_engine` in the first cell of this notebook to use it below.

In [ ]:
engine = create_engine('sqlite:///DisasterResponse.db')
df.to_sql('Disasterres', engine, index=False)

### 8. Use this notebook to complete `etl_pipeline.py`
Use the template file attached in the Resources folder to write a script that runs the steps above to create a database based on new datasets specified by the user. Alternatively, you can complete `etl_pipeline.py` in the classroom on the `Project Workspace IDE` coming later.